name: Upload repo files to Azure Blob

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Ensure container exists
        run: |
          az storage container create \
            --name mycontainer \
            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            --public-access off

      - name: Upload files to Azure Blob
        run: |
          az storage blob upload-batch \
            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            --destination mycontainer \
            --source . \
            --pattern "*" \
            --overwrite
