name: Upload repo files to Azure Blob

on:
  push:
    branches:
      - main   # change if you want another branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Step 3: Upload all files to Blob
      - name: Upload files to Azure Blob
        run: |
          for file in $(find . -type f ! -path "./.git/*" ! -path "./.github/*"); do
            echo "Uploading $file"
            az storage blob upload \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --container-name mycontainer \
              --name "$file" \
              --file "$file" \
              --overwrite
          done
